repos:
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.4.0
    hooks:
      - id: ansible-lint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4
    hooks:
      - id: terraform_validate
      - id: terraform_fmt