docker_users:
  - deploy

docker_packages:
  - docker.io
  - docker-compose-plugin

docker_daemon_config:
  log-driver: json-file
  log-opts:
    max-size: "10m"
    max-file: "3"
  live-restore: true
  userland-proxy: false
  no-new-privileges: true
