---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caliman
  namespace: caliman
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "caliman-ca-issuer"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "DENY" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header Referrer-Policy "no-referrer-when-downgrade" always;
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/enable-compression: "true"
spec:
  tls:
    - hosts:
        - caliman.local
      secretName: caliman-tls
  rules:
    - host: caliman.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caliman
                port:
                  number: 8080
