- name: Restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Apply sysctl
  ansible.builtin.command: sysctl --system
