stages:
  - test
  - security
  - build
  - push
  - deploy

lint:
  stage: test
  script:
    - pip install flake8
    - flake8 app/

trivy_scan:
  stage: security
  script:
    - trivy image caliman-app:latest

docker_build:
  stage: build
  script:
    - docker build -t caliman-app:$CI_COMMIT_SHA .

deploy:
  stage: deploy
  script:
    - echo "ArgoCD sync triggered"