env_name: dev

app_name: caliman
app_port: 8080
app_log_level: debug

node_exporter_version: "1.8.2"
node_exporter_port: 9100

docker_users:
  - deploy

docker_daemon_config:
  log-driver: json-file
  log-opts:
    max-size: "10m"
    max-file: "3"
  live-restore: true
  userland-proxy: false
  no-new-privileges: true

common_ssh_port: 22
common_ssh_permit_root_login: "no"
common_ssh_password_authentication: "no"
common_ssh_pubkey_authentication: "yes"

common_sysctl_settings:
  net.ipv4.tcp_syncookies: 1
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.default.rp_filter: 1
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.default.accept_redirects: 0
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.default.send_redirects: 0
  vm.swappiness: 10